site_name: "Windows-Errata-Optimizations"
site_url: "https://diegoalejandrosaenzfalcon.github.io/Windows-11-Professional/"
site_author: "Diego Alejandro Saenz Falcon"
copyright: "Copyright &copy; 2024 Diego Alejandro Saenz Falcon"

repo_url: "https://github.com/DiegoAlejandroSaenzFalcon/Windows-11-Professional"
repo_name: "DiegoAlejandroSaenzFalcon/Windows-11-Professional"

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: amber
    - scheme: slate
      primary: blue
      accent: amber

nav:
  - Inicio: index.md
  - START-HERE.md: START-HERE.md
  - issues/:
    - ms-cortana2-link-error: issues/ms-cortana2-link-error/README.md
    - ms-cortana2-no-malware: issues/ms-cortana2-no-malware/README.md
    - lenovo-ctrl-cortana2-link: issues/lenovo-ctrl-cortana2-link/README.md
    - ltsc-dev-services: issues/ltsc-dev-services/README.md
    - wifi-throughput-ltsc: issues/wifi-throughput-ltsc/README.md
    - windows-power-plan-ultimate: issues/windows-power-plan-ultimate/README.md
    - windows-telemetry-disable: issues/windows-telemetry-disable/README.md
    - windows-network-optimization: issues/windows-network-optimization/README.md
    - windows-visual-effects-performance: issues/windows-visual-effects-performance/README.md
    - rhel-dual-boot-partition: issues/rhel-dual-boot-partition/README.md
    - onedrive-remove-full: issues/onedrive-remove-full/README.md
    - searchhost-web-disable: issues/searchhost-web-disable/README.md
    - oem-bloat-services: issues/oem-bloat-services/README.md
    - edge-uninstall-full: issues/edge-uninstall-full/README.md

plugins:
  - search
